#Mise à jour via l'interface des paramètres
#Fri Apr 03 21:54:04 CEST 2026
app.auth.admin.login2faPath=/admin/auth/login-2fa
app.auth.admin.loginPath=/admin/auth/login
app.auth.admin.ssoAuthorizePath=/admin/auth/desktop/sso
app.auth.baseUrl=https://test-backend.remythibaut.fr
app.auth.bypass.enabled=false
app.auth.bypass.token=local-dev-token
app.auth.sso.timeout=180
app.auth.timeout=15
app.db.password=sananes
app.db.url=jdbc:sqlite:./data/neighborhood.db
app.db.user=sananes
app.plugins.path=plugins
app.sync.db.url=postgresql://projetAnnuel:VHvSlZHRULZ9jT75@remythibaut.fr:5432/projetAnnuel
app.sync.interval=60
app.update.checkUrl=https://test-backend.remythibaut.fr/api/updates/latest
app.update.timeout=30